// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: indentation.jflex

//CHECKSTYLE:OFF 

package org.scilab.modules.scinotes;

import java.io.IOException;
import javax.swing.text.Element;
import javax.swing.text.BadLocationException;

@javax.annotation.Generated("JFlex")

@SuppressWarnings("fallthrough")
public final class IndentScanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int INDENT = 2;
  public static final int WHITE = 4;
  public static final int TAB = 6;
  public static final int BEG = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4, 5
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\3\6\1\0\1\10\1\0\1\11\5\0\1\12"+
    "\12\6\5\0\1\6\1\0\32\6\2\0\1\11\1\0"+
    "\1\6\1\0\1\13\1\6\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\2\6\1\23\1\24\1\25\1\26"+
    "\2\6\1\27\1\30\1\31\1\32\1\6\1\33\1\6"+
    "\1\34\1\6\2\0\1\11\7\0\1\3\u01a2\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\2\0\1\2\1\3\15\2\2\1\1\4"+
    "\12\0\1\2\7\0\1\4\24\0\1\5\1\0\1\2"+
    "\10\0\1\2\6\0\1\6\1\0\1\6\1\2\7\0"+
    "\1\2\5\0\2\2\11\0\1\2\6\0\1\2\6\0"+
    "\1\2\1\0\2\2\1\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[128];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\35\0\72\0\127\0\164\0\221\0\0\0\0"+
    "\0\256\0\313\0\350\0\u0105\0\u0122\0\u013f\0\u015c\0\u0179"+
    "\0\u0196\0\u01b3\0\u01d0\0\u01ed\0\u020a\0\u0227\0\u0244\0\u0261"+
    "\0\u027e\0\u029b\0\u02b8\0\u02d5\0\u02f2\0\u030f\0\u032c\0\u0349"+
    "\0\u0366\0\313\0\u0383\0\u03a0\0\u03bd\0\u03da\0\u03f7\0\u0414"+
    "\0\u0431\0\u044e\0\u046b\0\u0488\0\u04a5\0\u04c2\0\u04df\0\u04fc"+
    "\0\u0519\0\u0536\0\u0553\0\u0570\0\u058d\0\u05aa\0\u05c7\0\u05e4"+
    "\0\u0601\0\u061e\0\u063b\0\u0658\0\u0675\0\u0692\0\u06af\0\u06cc"+
    "\0\u06e9\0\u046b\0\u0706\0\u0723\0\u0740\0\u075d\0\u077a\0\u0797"+
    "\0\u07b4\0\u07d1\0\u07ee\0\u080b\0\u0828\0\u0845\0\u0862\0\u087f"+
    "\0\u089c\0\u046b\0\u08b9\0\u08d6\0\u08f3\0\u0910\0\u092d\0\u094a"+
    "\0\u0967\0\u0984\0\u09a1\0\u09be\0\u09db\0\u09f8\0\u0a15\0\u0a32"+
    "\0\u0a4f\0\u0a6c\0\u0a89\0\u0aa6\0\u0ac3\0\u0ae0\0\u0afd\0\u0b1a"+
    "\0\u0b37\0\u0b54\0\u0b71\0\u0b8e\0\u0bab\0\u0bc8\0\u0be5\0\u0c02"+
    "\0\u0c1f\0\u0c3c\0\u0c59\0\u0c76\0\u0c93\0\u0cb0\0\u0ccd\0\u0cea"+
    "\0\u0d07\0\u0d24\0\u0d41\0\u0d5e\0\u0d7b\0\u0d98\0\u0db5\0\u046b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[128];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\35\0\2\7\1\10\2\0\1\7\1\11\2\12\1\13"+
    "\1\14\1\15\1\16\1\11\1\17\1\20\2\11\1\21"+
    "\3\11\1\22\1\11\1\23\1\24\1\11\1\25\1\11"+
    "\3\10\2\0\1\26\30\10\1\27\1\10\2\0\30\10"+
    "\3\7\2\0\31\7\1\30\1\7\2\0\1\30\27\7"+
    "\10\0\1\7\2\0\1\31\1\32\1\0\1\33\1\34"+
    "\2\0\1\35\3\0\1\36\1\0\1\37\1\40\1\0"+
    "\1\41\1\0\2\42\1\0\1\42\1\0\2\42\2\43"+
    "\24\42\10\0\1\7\36\0\1\44\32\0\1\7\2\0"+
    "\1\31\1\32\1\0\1\33\1\34\2\0\1\35\3\0"+
    "\1\36\1\45\1\37\1\40\1\0\1\41\11\0\1\7"+
    "\2\0\1\46\1\32\1\0\1\33\1\34\2\0\1\35"+
    "\3\0\1\36\1\0\1\37\1\40\1\0\1\41\11\0"+
    "\1\7\2\0\1\31\1\32\1\0\1\33\1\34\2\0"+
    "\1\35\1\47\1\0\1\50\1\36\1\0\1\37\1\40"+
    "\1\0\1\41\11\0\1\7\2\0\1\31\1\32\1\0"+
    "\1\33\1\34\2\0\1\35\3\0\1\51\1\0\1\37"+
    "\1\40\1\52\1\41\11\0\1\7\2\0\1\31\1\32"+
    "\1\0\1\33\1\53\2\0\1\35\3\0\1\36\1\0"+
    "\1\37\1\40\1\0\1\41\11\0\1\7\2\0\1\31"+
    "\1\32\1\0\1\33\1\34\2\0\1\35\3\0\1\36"+
    "\1\0\1\37\1\54\1\0\1\41\11\0\1\7\2\0"+
    "\1\31\1\32\1\0\1\55\1\34\2\0\1\35\3\0"+
    "\1\36\1\0\1\37\1\40\1\0\1\56\11\0\1\7"+
    "\2\0\1\31\1\32\1\0\1\33\1\34\2\0\1\35"+
    "\3\0\1\36\1\57\1\37\1\40\1\0\1\41\11\0"+
    "\1\7\2\0\1\31\1\32\1\0\1\33\1\34\1\0"+
    "\1\60\1\35\3\0\1\36\1\0\1\37\1\40\1\0"+
    "\1\41\6\0\1\26\30\0\1\27\34\0\1\30\3\0"+
    "\1\30\56\0\1\61\20\0\1\62\44\0\1\63\1\0"+
    "\1\64\35\0\1\65\3\0\1\66\21\0\1\7\46\0"+
    "\1\67\21\0\1\70\14\0\1\71\30\0\1\72\26\0"+
    "\1\73\22\0\2\42\24\0\2\44\1\7\2\0\30\44"+
    "\20\0\1\74\43\0\1\61\1\75\1\76\33\0\1\77"+
    "\21\0\1\100\46\0\1\53\1\0\1\67\30\0\1\101"+
    "\15\0\1\102\4\0\22\102\21\0\1\103\5\0\1\72"+
    "\30\0\1\104\1\0\1\64\30\0\1\73\1\105\46\0"+
    "\1\53\22\0\1\106\32\0\1\107\44\0\1\110\1\111"+
    "\33\0\1\112\21\0\1\113\46\0\1\7\32\0\1\114"+
    "\30\0\1\115\36\0\1\116\33\0\1\117\46\0\1\7"+
    "\22\0\1\120\44\0\1\121\20\0\1\122\32\0\1\123"+
    "\36\0\1\124\24\0\1\102\4\0\4\102\1\125\15\102"+
    "\14\0\1\126\36\0\1\127\34\0\1\130\11\0\1\112"+
    "\35\0\1\131\26\0\1\132\43\0\1\133\20\0\1\7"+
    "\32\0\1\134\36\0\1\135\35\0\1\136\31\0\1\137"+
    "\36\0\1\140\34\0\1\141\47\0\1\111\26\0\1\110"+
    "\35\0\1\142\31\0\1\122\21\0\1\102\4\0\7\102"+
    "\1\143\12\102\6\0\1\102\4\0\17\102\1\144\2\102"+
    "\31\0\1\145\32\0\1\146\21\0\1\147\34\0\1\150"+
    "\36\0\1\53\42\0\1\151\31\0\1\7\35\0\1\35"+
    "\44\0\1\66\33\0\1\152\32\0\1\153\21\0\1\154"+
    "\36\0\1\155\24\0\1\102\4\0\4\102\1\122\15\102"+
    "\6\0\1\102\4\0\12\102\1\156\7\102\22\0\1\157"+
    "\45\0\1\160\32\0\1\53\24\0\1\53\31\0\1\161"+
    "\40\0\1\162\45\0\1\163\32\0\1\7\30\0\1\164"+
    "\15\0\1\102\4\0\1\102\1\165\20\102\26\0\1\166"+
    "\30\0\1\167\37\0\1\170\35\0\1\171\30\0\1\172"+
    "\43\0\1\173\11\0\1\102\4\0\16\102\1\174\3\102"+
    "\25\0\1\53\37\0\1\75\35\0\1\175\30\0\1\7"+
    "\37\0\1\110\34\0\1\53\12\0\1\102\4\0\7\102"+
    "\1\176\12\102\30\0\1\7\12\0\1\102\4\0\13\102"+
    "\1\177\6\102\6\0\1\102\4\0\12\102\1\200\7\102";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3538];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\10\1\0\2\1\2\0\2\11\20\1\12\0\1\1"+
    "\7\0\1\1\24\0\1\1\1\0\1\1\10\0\1\1"+
    "\6\0\1\1\1\0\2\1\7\0\1\1\5\0\2\1"+
    "\11\0\1\1\6\0\1\1\6\0\1\1\1\0\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[128];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private ScilabDocument doc;
    private Element elem;

    public IndentScanner(ScilabDocument doc) {
    	this.doc = doc;
	this.elem = doc.getDefaultRootElement();
    }
   
    public int getIndentNumber(int lineNumber, char type) {
        if (lineNumber < 0) {
	    return 0;
	}
        try {
	     Element line = elem.getElement(lineNumber);
	     int startL = line.getStartOffset();
	     int endL = line.getEndOffset();	
	     yyreset(new ScilabDocumentReader(doc, startL, endL));
	     switch (type) {
	     	 case ' ':
	      	 yybegin(WHITE);
	      	 break;
	    	 case '\t':
	     	 yybegin(TAB);
	      	 break;
	     default:
		 yybegin(WHITE);
	     }
	     return yylex();
	} catch (IOException e) {
	     return 0;
	}
    }	

    public int getTabsAtBeginning(int pos) {
    	Element line = elem.getElement(pos);
	int startL = line.getStartOffset();
	int endL = line.getEndOffset();
	try {
	    yyreset(new ScilabDocumentReader(doc, startL, endL));
	    yybegin(BEG);
	    if (yylex() == 1) {
	        return yylength();
       	    }
	} catch (IOException e) {  
	    return 0;	
    	}
	return 0;
    }	    

    public void getIndentLevel(int pos, int[] level) {
    	Element line = elem.getElement(elem.getElementIndex(pos));
	int startL = line.getStartOffset();
	int endL = line.getEndOffset();
	level[0] = 0;
	level[1] = 0;
	try {
	    yyreset(new ScilabDocumentReader(doc, startL, endL));
	    yybegin(INDENT);
	    do {
	        switch (yylex()) {
	       	case 0:
	              break;
	       	case 1:
	             level[1]++;
		     break;
	       	case 2:
	             if (level[1] > 0) {
		         level[1]--;
		     } else {
	        	 level[0]++;
		     }
	             break;
	       	case 3:
	             if (level[1] == 0) {
		         level[0]++;
		         level[1]++;
		     }
                }	         
	    } while (zzMarkedPos != 0);
        } catch (IOException e) { } 	  
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public IndentScanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':  // fall through
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {   return 0;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return yylength();
            }
          // fall through
          case 7: break;
          case 2:
            { 
            }
          // fall through
          case 8: break;
          case 3:
            { return 0;
            }
          // fall through
          case 9: break;
          case 4:
            { return 1;
            }
          // fall through
          case 10: break;
          case 5:
            { return 2;
            }
          // fall through
          case 11: break;
          case 6:
            { return 3;
            }
          // fall through
          case 12: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
