#!/bin/sh
# autopkgtest check: Run the ode solver (interacting with the C compiler) and
# Checking the value of the solution in the middle of the interval is 1.
# (C) 2023 Pierre Gruet.
# Author: Pierre Gruet <pgt@debian.org>

set -e

# Run the example
scilab-cli -scihome $(mktemp -d) -f debian/tests/test_ode.sce -quit
# Check if we found (approximately) the solution.
grep -P '1\.00|0\.99' ode_solution.txt
