.TH "XML2Modelica" "1" "November 2017"
.SH NAME
XML2Modelica \- Scilab's translator from XML model to flat Modelica
.SH SYNOPSIS
.B XML2Modelica\fR \fB-o\fR <outputfile> <inputfile>
.SH OPTIONS
.TP
.B -o\fR <outputfile>
Set output file name
.TP
.B -init
Generate flat Modelica code for initialization
.SH AUTHOR
Manpage written by Julien Puydt for Debian
